### ISSUE TITLE
Doesn't work in win10 1903

### ISSUE THREAD

**Issue by madushan1000** [ipasimulator/ipasim#1]
Hi, 
When I open the SampleApp.app(or any other app) from your samples, I'm getting and library load error in the log window, I'm attaching the screenshot below. I'm going to try building the project myself later, but do you have any idea how this error might occur? 
![image](https://user-images.githubusercontent.com/4597144/61024394-1b1bb500-a3cb-11e9-89e7-d56ee0491f36.png)

**Comment by jjonescz** [comment]
This error means that some DLL is missing on your system (and it's not your problem, the emulator shouldn't expect the DLL to be there). Unfortunately, the error message reported by Windows from function `LoadPackagedLibrary` doesn't include name of the missing DLL. I will try to find out which DLL is causing this problem.
