### ISSUE TITLE
Release SampleGame

### ISSUE THREAD

**Issue by upintheairsheep** [ipasimulator/ipasim#11]
In the poster you made a sample game, but you forgot to release it.

**Comment by jjonescz** [comment]
Thanks! Not sure why I haven't released it previously. Added:
- [source code](https://github.com/ipasimulator/ipasim/tree/f616174c6b082237d3a853ce1206b2efa4fcc32a/samples/SampleGame)
- [binary](https://github.com/ipasimulator/ipasim/releases/download/v1.0/ipasim-samples-v1.0.zip)
