### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by solehfuddin** [ipasimulator/ipasim#3]
Hi, i have problem with valid certificate. Please update new certificate for me.
Many thanks

**Comment by jjonescz** [comment]
Updated in 352988f765551e159c75532bafa64c94c4efb601. Note that it is just a test certificate, so you can easily renew it yourself (see [Renewing a certificate in Microsoft Docs](https://docs.microsoft.com/en-us/previous-versions/br230260(v=vs.110)#renewing-a-certificate)). Also, invalid certificate shouldn't stop you from building the application, it just raises a warning.
