### ISSUE TITLE
The certificate is due

### ISSUE THREAD

**Issue by Jimmy2004** [ipasimulator/ipasim#4]

**Comment by Jimmy2004** [comment]
Powershell says that it cannot be installed because of the *.cer file has some issues.

**Comment by jjonescz** [comment]
This is just a development certificate, you can renew it yourself (see [Create a certificate for package signing](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)) and re-sign the app package (see [Sign an app package using SignTool](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool)).

I have updated the [latest release](https://github.com/ipasimulator/ipasim/releases/tag/v1.0.1) to include the renewed certificate.

Alternatively, you can follow these steps to renew the certificate yourself:

1. Download your chosen [release](https://github.com/ipasimulator/ipasim/releases), i.e., `ipasim-build-v*.zip`.
2. Extract it and navigate to folder with the package (`.msix` file).
3. Open elevated PowerShell in that folder.
4. Replace path to `signtool` depending on your installed Windows SDK in the following script (3rd line) and then execute it:
   ```ps1
   $cert = New-SelfSignedCertificate -Type Custom -Subject "CN=jjone" -KeyUsage DigitalSignature -FriendlyName "ipaSim" -CertStore Cert:\CurrentUser\My\ -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
   Export-PfxCertificate -cert $cert -FilePath key.pfx -Password $(ConvertTo-SecureString -String "ipaSim" -Force -AsPlainText)
   & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe' sign /fd sha256 /a /f key.pfx /p ipaSim .\IpaSimApp_*.msix
   Remove-Item key.pfx
   Export-Certificate -Cert $cert -FilePath (Get-ChildItem .\IpaSimApp_*.cer).name
   Remove-Item $cert.PSPath
   ```
5. The certificate (`.cer` file) should be renewed and the app package (`.msix` file) signed. You can now install the app by executing `./Add-AppDevPackage.ps1` as usual.
