### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by djsrv** [ipasimulator/ipasim#9]
Is ipasim released under an open-source license?

If not, would you please consider releasing it under the MIT License or similar and adding a LICENSE file, to encourage others to use and extend your excellent work? Thank you!

**Comment by jjonescz** [comment]
Yes, I added a license. Thanks for your interest. Please keep me posted what you use and/or extend ipasim into, looking forward.

**Comment by djsrv** [comment]
Awesome, thanks! I will keep you posted.
